import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faBusAlt,
  faSeedling,
  faWater,
  faVirus,
  faFirstAid,
  faBook,
  faLandmark,
  faFileWord,
  faFilePdf,
  faFileCsv,
  faFileExcel,
  faArrowCircleDown,
  faEye,
  faRobot,
  faFilePowerpoint,
  faFileImage,
  faChevronDown,
  faChevronUp,
  faCopy,
  faEnvelopeOpenText,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faBusAlt,
  faSeedling,
  faWater,
  faVirus,
  faFirstAid,
  faBook,
  faLandmark,
  faFileWord,
  faFilePdf,
  faFileCsv,
  faFileExcel,
  faArrowCircleDown,
  faEye,
  faRobot,
  faFilePowerpoint,
  faFileImage,
  faChevronDown,
  faChevronUp,
  faCopy,
  faEnvelopeOpenText
);
